# Generated by Django 3.0.4 on 2020-03-29 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uploadings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BlogCategory',
                'verbose_name_plural': 'BlogCategories',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'BlogPost', 'verbose_name_plural': 'BlogPosts'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blogpost',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='uuid',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_large',
            field=models.ImageField(blank=True, default='blog/post_default_large.jpg', null=True, upload_to=utils.uploadings.UploadToPathAndRename('image_large')),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_medium',
            field=models.ImageField(blank=True, default='blog/post_default_medium.jpg', null=True, upload_to=utils.uploadings.UploadToPathAndRename('image_medium')),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_small',
            field=models.ImageField(blank=True, default='blog/post_default_small.jpg', null=True, upload_to=utils.uploadings.UploadToPathAndRename('image_small')),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.uploadings.UploadToPathAndRename('image')),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogCategory'),
        ),
    ]
