# Generated by Django 3.0.4 on 2020-03-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
