# Generated by Django 3.0.4 on 2020-03-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_pages', '0002_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
