# Generated by Django 3.0.4 on 2020-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_pages', '0003_termspolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email_sent',
            field=models.TextField(default=None, null=True),
        ),
    ]
